### PR TITLE
Added gradient background animation

### PR DESCRIPTION
**Pull request by monotiller**
Feature request as of this comment: https://www.reddit.com/comments/sgsq3x/comment/huypzou/

It's nothing fancy but it does swirl around a little bit in the Steam Deck blue and purple colours!

### CODE REVIEW

**Comment by PeterHindes** [comment]
Thanks for submitting, I will check it out later today.

**Comment by PeterHindes** [comment]
Ok, I got a chance to look at it. It looks cool, but do you think it would be possible to match the style from valves own page?
image

**Comment by monotiller** [comment]
Thank you for the screenshot actually, for some reason I wasn't able to get that to appear on my browser, I get this instead:

image

I have just pushed my changes! Let me know what you think!

**Comment by PeterHindes** [comment]
Ok thats awesome, i will merge it in and publish it

**Comment by PeterHindes** [comment]
Should now be live

**Comment by monotiller** [comment]
Thank you!

**Comment by PeterHindes** [comment]
i’m looking at the site right now and it’s broken on safari ipados 
2354D33C-A829-43FA-AD01-FC39169CBFC5

https://user-images.githubusercontent.com/19994487/152245855-a100edf8-ba58-4503-b2ed-4a6821d04af5.MOV

after a minute

**Comment by monotiller** [comment]
Just done some investigating and it seems to be that the size of the gradient background is not updating when the viewport size changes.

https://user-images.githubusercontent.com/18310129/152316894-fc791d81-6b2d-496c-92bc-39acfb50f129.mp4

It might just need a little bit of javascript, I'll look into it!

**Comment by monotiller** [comment]
Hey, I seemed to have gotten it to fix the issue:

https://user-images.githubusercontent.com/18310129/152346382-596509d0-d059-4624-9a33-02fc026f0db0.mp4

I have opened a new pull request with the fixes here: #2. Hopefully this fixes it!

**Pull request merged**
