### PR TITLE
Fixed animated background

### PR DESCRIPTION
**Pull request by monotiller**
Also did a little code clean-up to make it a little easier to read!

`<div id="gradient-background">` tags were missing in the new javascript HTML code:
https://github.com/PeterHindes/steam-deck-countdown.live/blob/ab81c9e8d108800ec17eb0f485d345cf2e37f512/index.html#L232-L253

### CODE REVIEW

**Comment by PeterHindes** [comment]
Cool, Ill try it out
btw check out how they did the gradient on the [deck verified page](https://www.steamdeck.com/en/verified#handson)

**Comment by PeterHindes** [comment]
I kinda redesigned the gradient. hope your ok with that

**Comment by monotiller** [comment]
Oooh, fancy! Looks good, definitely more colourful. I learnt a lot about css animations doing this so I had a good time. Good luck with the site!

**Comment by PeterHindes** [comment]
Thanks for all your help 👍

**Pull request merged**
